export const appRoutes = {
    users: '/users',
    user_show: '/users/:id/show',
    user_edit: '/users/:id/edit',
    register: '/register',
    forgot: '/forgot',
    forgotSuccess: '/forgot-success',
    changePwd: '/change-password/:key',
    invalidKey: '/invalid-key',
    login: '/login',
    main: '/main',
    words_details: '/words/:id/details',
    notify_user: '/users/:userId/notify',
    notify_all: '/notify-all',
    notifications: '/notifications',
    notifications_show: '/notifications/:id/show',
    no_privileges: '/no-privileges',
    not_found: '/not-found',
    home: '/home',
    empty: '/'
};
